## Travis-CI Config
language: java
## Run integration tests.
script: "mvn verify"
branches:
  except:
    - gh-pages
jdk:
    - oraclejdk8
webhooks:
    urls:
      - https://webhooks.gitter.im/e/14df6243107094338d81
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: always     # options: [always|never|change] default: always